### ISSUE TITLE
Shell Wrapper Details

### ISSUE THREAD

**Issue by jamesgoodhouse** [muka/go-bluetooth#130]
I see in the readme it says "Shell wrappers for rfkill, btmgmt, hciconfig, hcitool"; are there more details for this? I see that there are some packages inside `hw/linux` but the only real shell wrapper I'm seeing is just inside `hw/linux/cmd`. I'm specifically interested in a wrapper for `hcitool`.

**Comment by muka** [comment]
Hi, the degree of support changed over time. Basically implementation follow the needs of the library. If you want to extend the wrapper I will be happy to review and merge a PR

**Comment by muka** [comment]
Closing, please reopen if you have updates. Thanks
