### ISSUE TITLE
[Bug] Discovery Filtering doesn't work

### ISSUE THREAD

**Issue by james-lawrence** [muka/go-bluetooth#140]
the following code doesn't actually filter devices by uuids.

```
	filter := adapter.NewDiscoveryFilter()
	filter.AddUUIDs(uuid)
	discovery, cancel, err := api.Discover(a, &filter)
```

if i put in a junk uuid I expect no devices to be found. (wasn't the case)
if i put in a valid id i expect the devices to be properly filtered. (wasn't the case)

**Comment by muka** [comment]
Hi @james-lawrence 
this is a recurring topic and seems to variate based on bluez version. Surely there is a bug, would you like to look into it and  provide a PR eventually?

Thank you

**Comment by james-lawrence** [comment]
definitely looks bluez related, at least the proper data is being sent to the service via dbus. thats highly annoying.

for now working around it by manually filtering. do you know where to send bluez bug reports? a cursory search didn't turn up much.

**Comment by muka** [comment]
You could try via the bluez mailing list or irc, see http://www.bluez.org/contact/

Let me know, thanks!

**Comment by muka** [comment]
Closing, please reopen if you have updates. Thanks
