### ISSUE TITLE
is it useable for android? 

### ISSUE THREAD

**Issue by MatejMagat305** [muka/go-bluetooth#141]
Hi I m coding in https://github.com/fyne-io/fyne, and it can run on android, it this library suitable for android?

**Comment by muka** [comment]
Hi, nice project! 
This library uses the dbus APIo of bluez. I guess android uses bluez for kernel communication but not sure about it. If you find it works i would be happy to add references to your project. Thanks

**Comment by MatejMagat305** [comment]
So I will try it, and I will reference

**Comment by MatejMagat305** [comment]
I m sorry it look like android need jni ............

**Comment by MatejMagat305** [comment]
Can I ask you? You have some experiences about bluetooth, I plan that I will create simple golang-jni interface to create server and client and sending data between both ........, do you planing some like that or not? Because I do not want duplicate work .......... and what is "minimal" interfaces to try embeded to your code ?

**Comment by jizhihaoSAMA** [comment]
Well, due to uncertainty and ignorance of Android and Bluetooth, I am sorry that I selected Python-Kivy and Python-bleak to solve this.
