### ISSUE TITLE
Mesh example

### ISSUE THREAD

**Issue by LLangh** [muka/go-bluetooth#142]
Are there any plans for an example for the mesh functionality of this library?

**Comment by muka** [comment]
I do not have a plan for it. If you have a chance to provide one I'd be
happy to review the PR. Thank you

>

**Comment by LarsLangholm** [comment]
Yeah. I might add one if I end up using it. However, I'm fairly new to the whole Go+Dbus+mesh combination, so the motivation for the question was mostly egotistical.

**Comment by muka** [comment]
I started the same way and enjoyed sharing along the way :)

**Comment by muka** [comment]
Closing, please reopen if you have updates. Thanks
