### ISSUE TITLE
Add send and recieve receive

### ISSUE THREAD

**Issue by MatejMagat305** [muka/go-bluetooth#146]
It is a little bit silly request, but it would be really helpful (at least for me) when you add something similar to server / client, but with sending and receive Massage, because I really do not know where I should give it.................., thank

**Comment by muka** [comment]
Hi @MatejMagat305 try starting  from here https://github.com/muka/go-bluetooth/blob/master/_examples/cmd/service.go and see how it goes

**Comment by MatejMagat305** [comment]
I understand that I could write according pictures, but I m not sure......, whether I can combinate.........
![client](https://user-images.githubusercontent.com/61238240/143571592-2b837299-09c0-48af-b425-87d00cc73575.png)
![server](https://user-images.githubusercontent.com/61238240/143571595-90061ac7-d7b0-4828-ac62-65bfdb21e600.png)
..

**Comment by muka** [comment]
Here you are mixing two different things. You need a service exposing characteristics on the server side that can receive and send data. The client can then connect and send receive. Try looking into the Bluetooth specs for am overview. Probably you'll need also two Bluetooth cards one to serve one for client

**Comment by MatejMagat305** [comment]
I m sorry for many question, but where https://github.com/muka/go-bluetooth/blob/master/examples/service/client.go are data sending?

**Comment by muka** [comment]
Sorry, personally I do not have such example code! If you find a way please consider adding an example to the library with a PR as it would help other users also!

Closing, please reopen if you have updates. Thanks
