### ISSUE TITLE
WriteValue: Operation failed with ATT error: 0x0e

### ISSUE THREAD

**Issue by sbinet** [muka/go-bluetooth#149]
hi,

I am using go-bluetooth@1c7f8793aa7e and when issueing a write command to a device (Aranet4), I *sometimes* receive:
```
aranet4: could not read data: could not read param=1: could not write command: Operation failed with ATT error: 0x0e
```

here is the place where this occurs:
- https://git.sr.ht/~sbinet/aranet4/tree/v0.5.0/item/device.go#L180
- https://git.sr.ht/~sbinet/aranet4/tree/v0.5.0/item/device.go#L217
- https://git.sr.ht/~sbinet/aranet4/tree/v0.5.0/item/device.go#L232

searching a bit around, I've found this issue:
- https://github.com/nettlep/gobbledegook/issues/12

which seems similar (although I do send the command with `"type":"request"`)

any ideas?

**Comment by muka** [comment]
No idea but this seems happening underneath the library itself. Can you reproduce using bluetoothctl or another client?

**Comment by sbinet** [comment]
I am not fluent in bluetooth.
would you have a few pointers forhow to achieve the equivalent of `WriteValue` with `bluetoothctl` ?

**Comment by muka** [comment]
I found this reference 
https://www.spinics.net/lists/linux-bluetooth/msg74637.html

I know it is possible but not much used to it :)
