### ISSUE TITLE
Is bluetooth device emulation/advertisement usable?

### ISSUE THREAD

**Issue by nanoscopic** [muka/go-bluetooth#150]
The main readme says that "Expose bluetooth service from go code" is unstable. Is this still currently true? Could you elaborate on what sort of unstability has been noticed and what to expect?

This seems to be a core feature of tinygo bluetooth that uses this library, and if there are issues with it I would like to know what the issues are before deciding to use it.

**Comment by muka** [comment]
If you decide to go for it and have feedback, PR and suggestions are always welcome!

**Comment by nanoscopic** [comment]
Thanks. My intent is to use this by way of tinygo bluetooth with NRF52840 usb dongle to make virtual bluetooth keyboard/mouse for an iOS device farm.

The rest of the project is already in Go, so I wanted the portion of it for this to use Go as well. I'll be trying it out and if it works well will integrate its use into the larger project.

If I notice any way to improve it I'll be happy to contribute both feedback and/or PRs. Thanks for the open welcome.

**Comment by muka** [comment]
Ok, good to know! I had a test setup but with different use-case, maybe is helpful https://github.com/muka/pi-wifi
