### ISSUE TITLE
List paired devices

### ISSUE THREAD

**Issue by lebck** [muka/go-bluetooth#164]
Hi! 

Maybe I'm missing something, but it seems that currently it's not possible to get a list of already paired devices.

I know I can get all nearby, paired devices by doing a discovery and filtering out all the non-paired devices, but I'd like to show all paired devices, regardless of whether they are nearby or not, and without the need to do a discovery first.

**Comment by muka** [comment]
I do not think this is possible, a Discovery is always needed. Maybe you could fetch cached devices but still via Discovery I guess.
