### ISSUE TITLE
Bluez 5.65 support

### ISSUE THREAD

**Issue by kkeijzer** [muka/go-bluetooth#168]
I'm using [itd](https://gitea.arsenm.dev/Arsen6331/itd), which depends on `go-bluetooth`. Recently, Debian bullseye updated Bluez to version 5.65, and ever since, it has stopped working.

I now get `MapToStruct: Field not found: Bonded` whenever I try to connect.

**Comment by Arsen6331** [comment]
This is currently blocking [Arsen6331/itd#22](https://gitea.arsenm.dev/Arsen6331/itd/issues/22)

**Comment by muka** [comment]
A generated version of bluez is available at `bluez/5.65` but need to be tested. Unfortunately I am missing the equipment to progress on the project.
