### ISSUE TITLE
Ignore missing fields in MapToStruct

### ISSUE THREAD

**Issue by Arsen6331** [muka/go-bluetooth#169]
Rather than returning `Field Not Found` from `MapToStruct`, ignore a field if it is not found. The current behavior has caused numerous issues for [ITD](https://gitea.arsenm.dev/Arsen6331/itd) when BlueZ has added a new field. The most recent of these issues resulted in #168. This change would theoretically allow new BlueZ versions to work, albeit without their new features, even though official support has not been added for them.

**Comment by muka** [comment]
The idea is to add the features and then have the release. Unfortunately I do not have much time to follow up so good to go as a patch. Thanks
