### ISSUE TITLE
Missing tags for version 5.64 and 5.65

### ISSUE THREAD

**Issue by ChromaMaster** [muka/go-bluetooth#174]
Hi, are the versions that support bluez 5.64 and 5.65 committed and ready to use? If so, could you create the tags `bluez-5.64` or `v5.64` and `bluez-5.65` or `v5.65` so those versions can be pinned in the go modules? 

Thanks

**Comment by muka** [comment]
Yes, could you provide a PR or a reference branch to merge with support for those releases?

**Comment by ChromaMaster** [comment]
I guess:
- Branch: https://github.com/muka/go-bluetooth/tree/bluez/5.64 (commit 1d8857e3b268676077765e86c45bfc7a7d1758a9) would be `bluez-5.64` or `v5.64` 
- Branch: https://github.com/muka/go-bluetooth/tree/bluez/5.65 (same commit as the above 1d8857e3b268676077765e86c45bfc7a7d1758a9) would be `bluez-5.65` or `v5.65`

**Comment by muka** [comment]
Done, sorry for the late update

**Comment by ChromaMaster** [comment]
@muka Hi, it's possible that you didn't push the tags? I can't see them

**Comment by muka** [comment]
Ohh yes, my fault. Just created the branches. TODO: automate new bluez releases
