### ISSUE TITLE
"Just works" pairing

### ISSUE THREAD

**Issue by gesaleh** [muka/go-bluetooth#18]
Does this lib works with this simple pairing ? "just works"

**Comment by muka** [comment]
There is no explicit api yet but can be added based on the dbus exposed one.

Do you have a device to test or use case to describe?

sent from my phone

Il 09 ott 2017 10:53 PM, "gesaleh" <notifications@github.com> ha scritto:

**Comment by gesaleh** [comment]
yes I have a device 
this is what i discovered 
need "just works" pairing no keyinput or display or pin asked
once paired i can read characteristics of the device

**Comment by muka** [comment]
That's great, I cannot work on it soon. If you can contribute with some code, I will review and merge it to the repository.

Thank you
