### ISSUE TITLE
hcisocket bindings

### ISSUE THREAD

**Issue by muka** [muka/go-bluetooth#21]
Setup bindings to `hcisocket` to handle device configurations

- https://github.com/paypal/gatt/blob/master/linux/hci.go
- https://github.com/currantlabs/ble/tree/master/linux/hci
- https://github.com/sandeepmistry/node-bluetooth-hci-socket
- https://github.com/nettlep/gobbledegook

**Comment by BlackGh0st** [comment]
This doc could also be very useful in this task
 - https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/mgmt-api.txt

**Comment by muka** [comment]
There is now a wrapper for `btmgmt` that allow to toggle most of the meaningful setting. 

Also I am experimenting with hci socket interface based on the `https://github.com/currantlabs/ble` package

**Comment by muka** [comment]
Closing for now as btmgm cover main needs, reopen when an impl is available
