### ISSUE TITLE
Pairing support (Agent)

### ISSUE THREAD

**Issue by muka** [muka/go-bluetooth#26]
Pairing support can be provided by `org.bluez.Agent1`. See

- https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/agent-api.txt
- https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/test/simple-agent

**Comment by LethalEthan** [comment]
Look on line 67 or line 74, on the simple-agent maybe you could utilise those functions, but I'm not quite sure if it will work.

**Comment by muka** [comment]
@mame82 Will attempt the integration thanks!

**Comment by muka** [comment]
Thanks to @cuu that has provided an implementation, closing
