### ISSUE TITLE
interface conversion issue for luxometer

### ISSUE THREAD

**Issue by saurabh-newera** [muka/go-bluetooth#33]
while running the example code I am facing this issue
//(running on ubuntu 16.04)
panic: interface conversion: interface {} is devices.LuxometerSensor, not *devices.LuxometerSensor

goroutine 1 [running]:
github.com/muka/go-bluetooth/devices.newLuxometerSensor(0xc4202e2680, 0xc4204099c0, 0x0, 0x0)
	/home/saurabh/.go/src/github.com/muka/go-bluetooth/devices/sensortag_luxometer.go:62 +0x1ff
github.com/muka/go-bluetooth/devices.NewSensorTag(0xc4202b9a70, 0x1, 0x1, 0xc4203189d0)
	/home/saurabh/.go/src/github.com/muka/go-bluetooth/devices/sensortag.go:231 +0x450
main.ConnectAndFetchSensorDetailAndData(0xc4202e52e0, 0x11, 0x659e0b, 0xb)
	/home/saurabh/examples/sensortag/adpater.go:93 +0x1ed
main.SensorTag()
	/home/saurabh/examples/sensortag/adpater.go:61 +0x7eb
main.main()
	/home/saurabh/examples/sensortag/adpater.go:24 +0x89
exit status 2

**Comment by muka** [comment]
Should be ok now, it was a wrong return in callback. Thank you!
