### ISSUE TITLE
interface conversion issue with the emitter

### ISSUE THREAD

**Issue by saurabh-newera** [muka/go-bluetooth#34]
while fetching sensor data:-
panic: interface conversion: interface {} is devices.SensorTagDataEvent, not api.DataEvent

goroutine 31 [running]:
main.ConnectAndFetchSensorDetailAndData.func1(0x75a180, 0xc4201e96c0)
	/home/saurabh/examples/sensortag/adpater.go:147 +0x1f7
created by github.com/muka/go-bluetooth/emitter.loop
	/home/saurabh/.go/src/github.com/muka/go-bluetooth/emitter/events.go:59 +0x205
exit status 2

**Comment by saurabh-newera** [comment]
Issue fixed:
inside :- examples/sensortag_info/main.go
- x := ev.GetData().(api.DataEvent)
+ x := ev.GetData().(devices.SensorTagDataEvent)

structure definition has changed in backend, but not updated in example code.

**Comment by saurabh-newera** [comment]
After 1-2 minutes sensors stop sending data(in connected state).
Sensor connectivity is also not stable. (After few minutes sensors got disconnected)

**Comment by muka** [comment]
Thank you, fixed. The connectivity issues may be related to many factors and probably will require more research on your side.
