### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by vizzyolog** [muka/go-bluetooth#90]
Hi! 
github.com/muka/go-bluetooth/hw/linux/hci
# github.com/muka/go-bluetooth/hw/linux/hci
hw/linux/hci/hci.go:7:9: undefined: socket.Down
hw/linux/hci/hci.go:12:9: undefined: socket.Up
hw/linux/hci/hci.go:17:9: undefined: socket.List

go version - go1.13.6 darwin/amd64
OSX - 10.15.2

I try 
go get -u -v ./...   
but this does not produce results

**Comment by Depau** [comment]
This library is for Linux, not macOS.

**Comment by vizzyolog** [comment]
I was hoping for a cross platform approach. Thank you
