### ISSUE TITLE
Broken in new Go versions (1.13+)

### ISSUE THREAD

**Issue by natdm** [muka/go-bluetooth#93]
Uses an out of date version of Logrus, which uses an out of date `/x/unix` import from Go, resulting in the build error:

```bash
omit@omit-MacBook-Pro go-bluetooth (master) $ make build
git submodule update
FILTER= go run gen/srcgen/main.go
# github.com/sirupsen/logrus
../../sirupsen/logrus/terminal_check_bsd.go:11:12: undefined: unix.IoctlGetTermios
make: *** [gen/run] Error 2
```

**Comment by muka** [comment]
Thank you for reporting this. I will fix it asap, if you can provide a PR I
will revise and merge

**Comment by muka** [comment]
Hi, 
I reviewed and updated the dependencies. I also never tried the bluez on mac, I am unsure if it even works.

Closing, please reopen if needed
Thanks
